# Generated by Django 4.1.7 on 2023-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='agree',
            field=models.BooleanField(blank=True, default=None, help_text='Agree with Terms and conditions'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='birthdate',
            field=models.DateField(blank=True, default=None, help_text='Please use the following format: <em>DD-MM-YYYY</em>.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='mobileno',
            field=models.IntegerField(blank=True, default=None, error_messages={'unique': 'The Geeks Field you entered is not unique'}, unique=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='review',
            field=models.FileField(default='Good', max_length=254, upload_to=None),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='salary',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
