# Generated by Django 4.1.7 on 2023-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinformation_address_userinformation_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='mobileno',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'The Geeks Field you entered is not unique'}, help_text='Please enter your mobile number here', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='review',
            field=models.FileField(default=None, help_text='Please upload file on your reviews', max_length=254, upload_to=None),
        ),
    ]
