# Generated by Django 4.1.7 on 2023-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userinformation_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='birthdate',
            field=models.DateField(blank=True, default=None, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='review',
            field=models.CharField(default=None, help_text='Please upload file on your reviews', max_length=300),
        ),
    ]
