# Generated by Django 4.0.3 on 2023-02-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinformation_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': 'User_Info'},
        ),
    ]
