# Generated by Django 4.0.3 on 2023-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': 'User_Information'},
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=5),
        ),
    ]
